# Exception

### `컴퓨터 시스템이 동작하는 도중에 예상하지 못한 사태로 실행 중인 프로그램이 영향을 받는 것`

![20220202192437](https://user-images.githubusercontent.com/78770230/152136103-2af904b1-5243-4670-b238-e3b738e8f892.jpg)
![20220202190124](https://user-images.githubusercontent.com/78770230/152136471-25f3b31b-483d-482c-942a-07b74e6f0b99.jpg)

## try블록
- 기본적으로 맨 먼저 실행되는 코드로 여기에서 발생한 예외는 catch 블록에서 처리된다.

## catch 블록
- try 블록에서 발생한 예외 코드나 예외 객체를 인수로 전달받아 그 처리를 담당한다.

## finally 블록
- try 블록에서 예외가 발생하건 안 하건 맨 마지막에 무조건 실행된다.

<br></br>


## 예외 처리 메커니즘
![20220202192907](https://user-images.githubusercontent.com/78770230/152136870-908ceda8-4cb4-49f8-8d27-2492383e0189.jpg)
![20220202192936](https://user-images.githubusercontent.com/78770230/152136876-2792b6bb-b03d-4faf-a7c7-6939993dfd33.jpg)

1. try 블록에 도달한 프로그램의 제어는 try 블록 내의 코드를 실행한다.
2. 예외가 발생한다면 catch핸들러는 catch 블록을 찾아가서 다음과 같은 순서로 적절한 catch 블록을 찾는다.
- 스택에서 try 블록과 가장 가까운 catch 블록부터 차례대로 검사
- 적절한 catch 블록을 찾지 못하면, 바로 다음 바깥쪽 try 블록 다음에 위치한 catch 블록을 차례대로 검사
- 가장 바깥쪽 try블록까지 계속해서 검사
- 적절한 catch 블록을 찾지 못하면, 예외는 처리되지 못함
3. 적절한 catch 블록을 찾게 되면, throw 문의 피연산자는 예외 객체의 형식 매개변수로 전달된다.
4. 모든 예외 처리가 끝나면 프로그램의 제어는 예외 처리문 바로 다음으로 이동한다.



#### 출처 : 
데어 프로그래밍 JAVA강의 <https://www.easyupclass.com/course/274/about>,  
TCPSCHOOL <http://www.tcpschool.com/java/java_exception_intro>
